import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from '../app/server.js';
import {digest} from '../app/admin-auth.js';
import {createCompassHandler} from '../app/compass/handler.js';
import {createCompassStore} from '../app/compass/store.js';
import {createCompassContent,publishedArticles} from '../app/compass/content.js';
import {validateAnswers} from '../app/compass/profile.js';
import {recommend,achievements,recommendations} from '../app/compass/recommendations.js';
import {guide,minimalContext} from '../app/compass/ai.js';
import {shareCard,questionnaire} from '../app/compass/views.js';
const csrf='a'.repeat(64),alice='b'.repeat(64),bob='c'.repeat(64),free='d'.repeat(64),origin='https://gold.example';
const content=await createCompassContent({directory:{map:async()=>({people:[{id:'real-one',slug:'river-teacher',display_name:'River Teacher',short_introduction:'Published creator'}],regions:[{person_id:'real-one',name:'Maine'}],topics:[{person_id:'real-one',name:'River panning'}]}),compassResources:async()=>[]},store:{destinations:async()=>[]}})();
const empty=()=>({answers:{},revision:0,step:0,completedAt:null,inventory:[],activity:[]});
function memoryStore(){const rows=new Map(),caches=new Map();const load=id=>structuredClone(rows.get(id)||empty());return {rows,ready:async()=>true,load:async id=>load(id),save:async(id,{patch,revision,step,finish})=>{const s=load(id);if(s.revision!==revision){const e=new Error('Conflict');e.status=409;throw e;}Object.assign(s,{answers:{...s.answers,...patch},revision:revision+1,step,completedAt:finish?new Date():s.completedAt});rows.set(id,s);caches.delete(id);},feedback:async(id,item,action)=>{const s=load(id);let a=s.activity.find(a=>a.item_id===item);if(!a){a={item_id:item};s.activity.push(a);}const key={save:'saved',complete:'completed',dismiss:'dismissed',known:'already_known',more:'preference',less:'preference',unsave:'saved',undo:'completed'}[action];a[key]=['unsave','undo'].includes(action)?0:action==='less'?-1:1;rows.set(id,s);caches.delete(id);},cache:async(id,key)=>caches.get(id)?.key===key?caches.get(id).result:null,putCache:async(id,key,result)=>caches.set(id,{key,result}),refresh:async id=>caches.delete(id),reset:async id=>{const s=load(id);for(const a of s.activity)Object.assign(a,{dismissed:0,already_known:0,preference:0});rows.set(id,s);caches.delete(id);},erase:async id=>{rows.delete(id);caches.delete(id);},destinations:async()=>[]};}
async function fixture(t,options={}){const store=options.store||memoryStore(),sessions=new Map([[alice,{id:'alice',username:'Alice',effective_level:'subscriber',csrf_token_hash:digest(csrf)}],[bob,{id:'bob',username:'Bob',effective_level:'subscriber',csrf_token_hash:digest(csrf)}],[free,{id:'free',username:'Free',level:'subscriber',effective_level:'free',csrf_token_hash:digest(csrf)}]]);const server=createServer({compass:createCompassHandler({members:{session:async raw=>sessions.get(raw)},config:{origin},store,content:async()=>content,ai:null,log:()=>{},...options})});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));return {store,request:(path,fields,session=alice,headers={})=>fetch(`http://127.0.0.1:${server.address().port}${path}`,{redirect:'manual',headers:{Cookie:`__Host-gold-member=${session}; __Host-gold-form=${csrf}`,...(fields?{Origin:origin,'Content-Type':'application/x-www-form-urlencoded'}:{}),...headers},...(fields?{method:'POST',body:new URLSearchParams({csrf,...fields})}:{})})};}
test('subscriber onboarding persists through new requests, returns to dashboard, and isolates accounts',async t=>{const {request,store}=await fixture(t);assert.equal((await request('/compass/')).headers.get('location'),'/compass/profile/?step=0');let r=await request('/compass/profile/',{revision:'0',step:'0',intent:'next',experience:'new',account_id:'bob'});assert.equal(r.status,303);assert.equal(store.rows.get('alice').answers.experience,'new');assert.equal(store.rows.has('bob'),false);r=await request('/compass/profile/?step=0');assert.match(await r.text(),/value="new" checked/);r=await request('/compass/profile/',{revision:'1',step:'6',intent:'finish',learning:'articles'});assert.equal(r.headers.get('location'),'/compass/?welcome=1');r=await request('/compass/');assert.equal(r.status,200);assert.match(await r.text(),/Welcome to your trail, Alice/);assert.equal((await request('/compass/',null,bob)).headers.get('location'),'/compass/profile/?step=0');assert.ok(store.rows.get('alice').completedAt);});
test('premium routes reject anonymous and free accounts, forged origin, CSRF and missing schema',async t=>{const {request,store}=await fixture(t);assert.equal((await request('/compass/passport/',null,'0'.repeat(64))).headers.get('location'),'/login/');assert.equal((await request('/compass/profile/',{revision:'0',step:'0',intent:'next'},free)).status,403);assert.equal((await request('/compass/profile/',{revision:'0',step:'0',intent:'next'},alice,{Origin:'https://evil.example'})).status,403);assert.equal((await request('/compass/profile/',{csrf:'f'.repeat(64),revision:'0',step:'0',intent:'next'})).status,403);assert.equal(store.rows.size,0);const other=await fixture(t,{store:{ready:async()=>false}});assert.equal((await other.request('/compass/')).status,503);});
test('profiles differ meaningfully, suppress owned and dismissed equipment, use only valid links',()=>{const a=empty();a.answers={experience:'new',goal:'first',interests:['river'],region:'Maine',equipment:['pan','classifier']};const b=empty();b.answers={experience:'expert',goal:'detecting',interests:['detecting'],equipment:['sluice']};const ra=recommend(a,content),rb=recommend(b,content);assert.notDeepEqual(ra.products.map(x=>x.id),rb.products.map(x=>x.id));assert.notEqual(ra.adventure.id,rb.adventure.id);assert.ok(ra.creators[0].reasons.some(x=>/region/.test(x)));for(const x of [...ra.products,...rb.products,...ra.lessons,...ra.creators])assert.ok(content.records.some(r=>r.id===x.id&&r.url));assert.ok(ra.products.every(x=>!['pan','classifier'].includes(content.records.find(r=>r.id===x.id).category)));a.inventory.push({category:'snuffer'});assert.equal(recommend(a,content).products.length,0);a.activity.push({item_id:ra.adventure.id,completed:1},{item_id:ra.creators[0].id,dismissed:1});const next=recommend(a,content);assert.ok(!next.lessons.some(x=>x.id===ra.adventure.id));assert.ok(!next.creators.some(x=>x.id===ra.creators[0].id));});
test('budget compares only established matching currencies, preserves unknown prices honestly',()=>{const state=empty();state.answers={goal:'first',budget:20,currency:'USD'};const c={records:[{id:'product:expensive',kind:'product',title:'Pan',category:'pan',tags:[],price:30,currency:'USD'},{id:'product:unknown',kind:'product',title:'Pan',category:'pan',tags:[],price:30,currency:null}],version:'1'};assert.deepEqual(recommend(state,c).products.map(x=>x.id),['product:unknown']);});
test('profile validation is bounded, nullable and rejects equipment contradictions or injected fields',()=>{assert.deepEqual(validateAnswers({experience:null},0),{experience:null});assert.throws(()=>validateAnswers({equipment:['none','pan']},3));assert.throws(()=>validateAnswers({account_id:'victim'},0));assert.throws(()=>validateAnswers({favoriteCreators:['creator:made-up']},7,content.records));assert.throws(()=>validateAnswers({travelMiles:-1},2));assert.throws(()=>validateAnswers({aiConsent:'yes'},7));});
test('recommendation cache is per account and invalidated by profile, activity and content revisions',async()=>{const store=memoryStore(),a=empty();await recommendations(store,'alice',a,content);let puts=0;const wrapped={...store,putCache:async(...args)=>{puts++;return store.putCache(...args);}};await recommendations(wrapped,'alice',a,content);assert.equal(puts,0);await recommendations(wrapped,'bob',a,content);assert.equal(puts,1);a.answers.goal='locations';await recommendations(wrapped,'alice',a,content);assert.equal(puts,2);await recommendations(wrapped,'alice',a,{...content,version:'changed'});assert.equal(puts,3);});
test('passport stamps require real activity; share image omits private details unless name explicitly supplied',()=>{const state=empty();state.answers={postalCode:'PRIVATEZIP',discoveries:'ounce',region:'PRIVATEHOME',accessibility:'PRIVATENOTE'};assert.ok(achievements(state,content.records).every(x=>!x.earned));state.completedAt=new Date();state.activity=[{item_id:'article:black-sands',completed:1}];assert.equal(achievements(state,content.records).find(x=>x.id==='sand').earned,false);state.activity.push({item_id:'challenge:black-sand',completed:1});assert.equal(achievements(state,content.records).find(x=>x.id==='sand').earned,true);const svg=shareCard(state,content.records);assert.doesNotMatch(svg,/PRIVATEZIP|PRIVATEHOME|PRIVATENOTE|ounce/);assert.match(shareCard(state,content.records,'My chosen name'),/My chosen name/);});
test('feedback rejects invented IDs and challenges cannot be awarded by generic feedback',async t=>{const {request}=await fixture(t);assert.equal((await request('/compass/feedback/',{item:'article:invented',action:'complete'})).status,400);assert.equal((await request('/compass/feedback/',{item:'challenge:black-sand',action:'complete'})).status,400);assert.equal((await request('/compass/challenge/',{item:'challenge:black-sand',answer:'no'})).status,400);});
test('expired members can export or erase only their own data, without premium feature access',async t=>{const {request,store}=await fixture(t);store.rows.set('free',{...empty(),answers:{region:'My region'}});store.rows.set('alice',{...empty(),answers:{region:'Alice region'}});assert.equal((await request('/compass/',null,free)).status,403);const r=await request('/compass/export/',{account_id:'alice'},free);assert.equal(r.status,200);assert.match(await r.text(),/My region/);assert.equal((await request('/compass/delete/',{confirmation:'DELETE COMPASS',account_id:'alice'},free)).status,200);assert.equal(store.rows.has('free'),false);assert.equal(store.rows.has('alice'),true);});
test('AI cannot select fabricated IDs, failure falls back, and private fields stay out of context',async()=>{const state=empty();state.answers={aiConsent:true,region:'Maine',postalCode:'SECRETZIP',discoveries:'ounce',accessibility:'SECRETNOTE',interests:['river']};assert.doesNotMatch(JSON.stringify(minimalContext(state)),/SECRET|ounce/);let payload;const result=await guide({question:'river sampling',state,content,config:{model:'configured-model',key:'test'},fetcher:async(url,opts)=>{payload=JSON.parse(opts.body);return{ok:true,json:async()=>({output:[{content:[{type:'output_text',text:'{"record_ids":["article:invented"]}'}]}]})};}});assert.match(result.mode,/unavailable/);assert.ok(result.records.every(x=>content.records.some(r=>r.id===x.id)));assert.equal(payload.store,false);assert.doesNotMatch(JSON.stringify(payload),/SECRET|ounce/);let calls=0;state.answers.aiConsent=false;await guide({question:'river',state,content,config:{model:'test',key:'test'},fetcher:async()=>calls++});assert.equal(calls,0);});
test('MariaDB profile writes lock account, reject stale revisions, and bind all owner IDs; deletion is scoped',async()=>{const queries=[];let rollback=false,commit=false;const db={query:async()=>[],getConnection:async()=>({beginTransaction:async()=>{},commit:async()=>commit=true,rollback:async()=>rollback=true,release:()=>{},query:async(sql,args)=>{queries.push([sql,args]);if(sql.startsWith('SELECT answers_json'))return[{revision:2,answers_json:'{}'}];return [];}})};const store=createCompassStore(db);await assert.rejects(store.save('alice',{patch:{region:'New'},revision:1,step:2,finish:false}),/another screen/);assert.equal(commit,false);assert.equal(rollback,true);assert.ok(!queries.some(([sql])=>sql.startsWith('INSERT')));queries.length=0;await store.erase('alice');const deletes=queries.filter(([sql])=>sql.startsWith('DELETE'));assert.equal(deletes.length,5);for(const [sql,args]of deletes){assert.match(sql,/WHERE account_id=\?/);assert.deepEqual(args,['alice']);}});
test('all seven steps are editable and optional, HTML escapes profile text and records',()=>{const state=empty();state.answers={region:'<script>alert(1)</script>'};for(let i=0;i<8;i++){const html=questionnaire(state,csrf,i,content.records);assert.match(html,/name="revision"/);assert.match(html,/Save & pause/);assert.doesNotMatch(html,/<script>alert/);assert.match(html,/Your Compass privacy/);}assert.equal(publishedArticles().length,5);});
test('configured AI can only select eligible existing records and respects per-account usage limit',async()=>{const state=empty();state.answers={aiConsent:true,equipment:['pan'],interests:['river']};let calls=0;const fetcher=async(url,opts)=>{calls++;const p=JSON.parse(opts.body),ids=p.text.format.schema.properties.record_ids.items.enum;assert.ok(!ids.some(id=>content.records.find(r=>r.id===id)?.category==='pan'));return{ok:true,json:async()=>({output:[{content:[{type:'output_text',text:JSON.stringify({record_ids:['article:where-gold-settles']})}]}]})};};const result=await guide({question:'read a stream',state,content,config:{key:'test',model:'explicitly-configured'},fetcher});assert.match(result.mode,/AI-assisted/);assert.equal(result.records[0].id,'article:where-gold-settles');await guide({question:'river',state,content,config:{key:'test',model:'test'},fetcher,allow:async()=>false});assert.equal(calls,1);});
test('Compass CSS/JS remain static assets and profile responses disable caching and framing',async t=>{const {request}=await fixture(t);const css=await request('/compass.css');assert.equal(css.status,200);assert.match(css.headers.get('content-type'),/text\/css/);const script=await request('/compass.js');assert.match(script.headers.get('content-type'),/javascript/);const r=await request('/compass/profile/');assert.equal(r.headers.get('cache-control'),'private, no-store');assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.equal(r.headers.get('x-robots-tag'),'noindex');});

test('reading-only interests do not trigger unnecessary gear purchases',()=>{const s=empty();s.answers={experience:'experienced',interests:['history','geology'],goal:'learn'};assert.equal(recommend(s,content).products.length,0);});
