import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from '../app/server.js';
import {digest} from '../app/admin-auth.js';
import {createCompassHandler} from '../app/compass/handler.js';
import {createCompassStore} from '../app/compass/store.js';
import {ProfileError} from '../app/compass/profile.js';
import {dashboardModules,defaultLayout,layoutFromForm,validateLayout} from '../app/compass/dashboard-layout.js';
import {dashboardExample} from '../app/compass/demo.js';
import {fingerprint} from '../app/compass/recommendations.js';
import {dashboard} from '../app/compass/views.js';
const csrf='a'.repeat(64),session='b'.repeat(64),origin='https://gold.example';
const state=()=>({answers:{experience:'new',region:'PRIVATE REGION',postalCode:'PRIVATEZIP',discoveries:'PRIVATEFIND'},revision:3,step:7,completedAt:'2026-10-10',inventory:[{category:'pan',quantity:1}],activity:[]});
function fields(layout=defaultLayout()){return Object.fromEntries([['csrf',csrf],['revision','3'],['intent','save'],...layout.order.flatMap((id,i)=>[['position_'+id,String(i+1)],...(layout.hidden.includes(id)?[]:[['visible_'+id,'yes']])])]);}
async function fixture(t){const rows=new Map([['alice',state()],['bob',state()]]),calls=[];const store={ready:async()=>true,load:async id=>structuredClone(rows.get(id)),saveLayout:async(id,value,revision)=>{const s=rows.get(id);if(s.revision!==revision)throw new ProfileError('Reload before saving.',409);s.answers.dashboardLayout=value;s.revision++;calls.push(id);},cache:async()=>null,putCache:async()=>{}};const sample=await dashboardExample();let sessions=0;const server=createServer({compass:createCompassHandler({members:{session:async token=>{sessions++;return token===session?{id:'alice',username:'Alice',effective_level:'subscriber',csrf_token_hash:digest(csrf)}:token==='c'.repeat(64)?{id:'free',effective_level:'free'}:null;}},config:{origin},store,content:async()=>({records:sample.records,version:'test'}),ai:null,log:()=>{}})});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));return {rows,calls,sessions:()=>sessions,request:async(path,values=null,token=session,headers={})=>fetch(`http://127.0.0.1:${server.address().port}${path}`,{redirect:'manual',headers:{Cookie:`__Host-gold-member=${token}; __Host-gold-form=${csrf}`,...(values?{Origin:origin,'Content-Type':'application/x-www-form-urlencoded'}:{}),...headers},...(values?{method:'POST',body:new URLSearchParams(values)}:{})})};}
test('registry covers every requested module and validates complete bounded layouts',()=>{assert.equal(dashboardModules.length,36);assert.equal(new Set(dashboardModules.map(m=>m.id)).size,36);const value=defaultLayout();assert.deepEqual(validateLayout(value),value);for(const bad of [{...value,order:value.order.slice(1)},{...value,hidden:['invented']},{...value,order:value.order.map(()=>value.order[0])},{...value,version:2}])assert.throws(()=>validateLayout(bad));const f=new URLSearchParams(fields());f.set('position_invented','1');assert.throws(()=>layoutFromForm(f));});
test('native layout form supports hiding, reordering, and restoring defaults',()=>{const value=defaultLayout();value.order.reverse();value.hidden=['guide','vault'];assert.deepEqual(layoutFromForm(new URLSearchParams(fields(value))),value);assert.deepEqual(layoutFromForm(new URLSearchParams({intent:'defaults'})),defaultLayout());const f=new URLSearchParams(fields());f.set('visible_vault','anything');assert.throws(()=>layoutFromForm(f));});
test('member layout survives new sessions, isolates owners and preserves existing profile fields',async t=>{const f=await fixture(t),layout=defaultLayout();layout.order.reverse();layout.hidden=['progress','vault'];const before=structuredClone(f.rows.get('alice'));const response=await f.request('/compass/layout/',{...fields(layout),account_id:'bob'});assert.equal(response.status,303);assert.equal(response.headers.get('location'),'/compass/?layout_saved=1');assert.deepEqual(f.calls,['alice']);assert.deepEqual(f.rows.get('alice').answers.dashboardLayout,layout);assert.equal(f.rows.get('alice').answers.postalCode,before.answers.postalCode);assert.deepEqual(f.rows.get('alice').inventory,before.inventory);assert.equal(f.rows.get('alice').completedAt,before.completedAt);assert.equal(f.rows.get('bob').answers.dashboardLayout,undefined);const html=await(await f.request('/compass/')).text();assert.match(html,/data-module="vault"[^>]* hidden/);assert.ok(html.indexOf('data-module="account"')<html.indexOf('data-module="next"'));assert.doesNotMatch(html,/PRIVATEZIP|PRIVATEFIND/);assert.equal((await f.request('/compass/layout/',fields(layout))).status,409);});
test('layout endpoint enforces membership, method, origin, and CSRF',async t=>{const f=await fixture(t);assert.equal((await f.request('/compass/layout/')).status,405);assert.equal((await f.request('/compass/layout/',fields(),'c'.repeat(64))).status,403);assert.equal((await f.request('/compass/layout/',fields(),'d'.repeat(64))).headers.get('location'),'/login/');assert.equal((await f.request('/compass/layout/',fields(),session,{Origin:'https://evil.example'})).status,403);assert.equal((await f.request('/compass/layout/',{...fields(),csrf:'f'.repeat(64)})).status,403);assert.deepEqual(f.calls,[]);});
test('public demonstration bypasses all member storage and session access and does not accept submissions',async t=>{const f=await fixture(t);const response=await f.request('/compass/demo/');assert.equal(response.status,200);const html=await response.text();assert.match(html,/example data/);assert.doesNotMatch(html,/PRIVATE REGION|PRIVATEZIP|PRIVATEFIND|name="csrf"|action="\/compass\/feedback\/"/);assert.match(html,/data-demo-action="save" disabled/);assert.equal(f.sessions(),0);assert.equal((await f.request('/compass/demo/',fields())).status,405);assert.equal(f.sessions(),0);});
test('examples personalize actual public records and suppress owned products',async()=>{const river=await dashboardExample(),detecting=await dashboardExample('detecting');assert.notEqual(river.result.persona,detecting.result.persona);assert.notDeepEqual(river.result.lessons,detecting.result.lessons);for(const sample of [river,detecting]){for(const item of [...sample.result.lessons,...sample.result.creators,...sample.result.products])assert.ok(sample.records.some(r=>r.id===item.id&&r.url));for(const item of sample.result.products)assert.ok(!sample.state.answers.equipment.includes(sample.records.find(r=>r.id===item.id).category));}});
test('layout changes leave cached recommendation fingerprints unchanged',()=>{const s=state(),catalog={version:'test'},before=fingerprint(s,catalog);s.answers.dashboardLayout=defaultLayout();assert.equal(fingerprint(s,catalog),before);s.answers.goal='first';assert.notEqual(fingerprint(s,catalog),before);});
test('MariaDB layout transaction preserves answers, binds session owner, and rejects stale writes',async()=>{const queries=[];let commits=0,rollbacks=0;const original={region:'Maine',equipment:['pan'],aiConsent:false};const db={getConnection:async()=>({beginTransaction:async()=>{},commit:async()=>commits++,rollback:async()=>rollbacks++,release:()=>{},query:async(sql,args)=>{queries.push([sql,args]);return sql.startsWith('SELECT answers_json')?[{answers_json:JSON.stringify(original),revision:4}]:[];}})};const store=createCompassStore(db);await store.saveLayout('alice',defaultLayout(),4);const [sql,args]=queries.find(([sql])=>sql.startsWith('UPDATE'));assert.match(sql,/WHERE account_id=\?/);assert.equal(args[1],'alice');const saved=JSON.parse(args[0]);assert.equal(saved.aiConsent,false);assert.deepEqual(saved.equipment,['pan']);assert.deepEqual(saved.dashboardLayout,defaultLayout());assert.ok(!queries.some(([sql])=>/onboarding_step|completed_at|DELETE|INSERT/.test(sql)));assert.equal(commits,1);queries.length=0;await assert.rejects(store.saveLayout('alice',defaultLayout(),3),e=>e.status===409);assert.equal(rollbacks,1);assert.ok(!queries.some(([sql])=>sql.startsWith('UPDATE')));});
test('vault and field previews contain no sensitive-entry controls or functional claims',async()=>{const sample=await dashboardExample(),html=dashboard(null,sample.state,sample.result,sample.records,'',false,{demo:true});for(const id of ['vault','finds','journal','photos','planner']){const card=html.split(`data-module="${id}"`)[1].split('</section>')[0];assert.doesNotMatch(card,/<input|<textarea|<form|type="file"/);assert.match(card,/Future preview/);}assert.match(html,/Zero-knowledge encryption is not implemented/);assert.equal((html.match(/data-module="/g)||[]).length,36);});
