import {escapeHtml as h} from '../directory-views.js';
import {experience,equipment,goals,interests,ownedCategories} from './profile.js';
import {achievements,activityMap} from './recommendations.js';
import {dashboardModules,dashboardGroups,defaultVisible,layoutFor} from './dashboard-layout.js';
import {cards,form,hidden,link} from './components.js';
const note=t=>`<p class="dashboard-note">${h(t)}</p>`;
const preview=(copy,sample='')=>`<p>${h(copy)}</p>${sample?`<div class="dashboard-example"><span class="eyebrow">ILLUSTRATIVE EXAMPLE</span><p>${h(sample)}</p></div>`:''}${note('Preview only · this tool does not save or retrieve information yet.')}`;
export function renderDashboard(member,state,result,records,csrf,{demo=false,persona='river',reveal=false,saved=false}={}){
 const layout=layoutFor(state),activity=activityMap(state),get=id=>records.find(r=>r.id===id),savedRecords=kind=>records.filter(r=>r.kind===kind&&activity.get(r.id)?.saved),completed=records.filter(r=>['article','video'].includes(r.kind)&&activity.get(r.id)?.completed),stamps=achievements(state,records),owned=[...ownedCategories(state.answers,state.inventory)],articleCount=records.filter(r=>r.kind==='article').length;
 const render=(items,limit=2)=>cards(items,records,state,csrf,{demo,limit});
 const existing=(rows,empty)=>rows.length?render(rows.map(r=>({id:r.id,reasons:[]})),3):`<p>${h(empty)}</p>`;
 const a=get(result.adventure?.id),favorite=records.filter(r=>r.kind==='creator'&&(state.answers.favoriteCreators?.includes(r.id)||activity.get(r.id)?.saved));
 const content={
  next:a?`<h3 class="dashboard-adventure-title">${h(a.title)}</h3><p>${h(a.summary)}</p><p class="compass-reason">${h(result.adventure.reasons.join(' '))}</p><p><strong>From your pack:</strong> ${h(owned.map(k=>equipment[k]).join(', ')||'No equipment recorded. Reading requires no purchase.')}</p><a class="gold-button" href="${h(a.url)}"${a.external?' target="_blank" rel="noopener noreferrer"':''}>Start my adventure →</a>`:'<p>You’ve completed or set aside the available lessons. Explore your passport or adjust your preferences.</p><a href="/compass/passport/">Open my passport</a>',
  progress:`<div class="dashboard-tally"><strong>${completed.length}</strong><span>lesson${completed.length===1?'':'s'} marked complete</span></div><progress value="${completed.filter(r=>r.kind==='article').length}" max="${Math.max(articleCount,1)}" aria-label="Completed articles from the current library"></progress><p>${completed.filter(r=>r.kind==='article').length} of ${articleCount} published articles completed. This records your activity, not a skill certification.</p>${demo?note('Sample completion history for this example profile.'):'<a href="/compass/passport/">Review completed lessons</a>'}`,
  maps:'<div class="dashboard-map-sketch" aria-hidden="true"><span>⌖</span><i>≈</i><b>✦</b></div><p>Explore where creators cover gold country. These dots describe creator coverage, not approved prospecting sites.</p><a href="/prospectors/?view=map">Open the creator coverage map →</a>'+note('Personal saved map layers are a future feature.'),
  locations:existing(savedRecords('destination'),'No saved locations with current access evidence. A river mentioned in a video is not an access permission.')+note('Only destinations in the vetted site catalog can appear here.'),
  river:preview('A future workspace for comparing river geology, source material, and access requirements.','Research outline: watershed → gravel and bedrock → published evidence → land manager and access checks.'),
  regional:preview('Regional reading collections will connect relevant creators, articles, and checked access information.',`Example collection focus: ${state.answers.region||'your home region'} · stream reading · sampling · seasonal trip planning.`),
  history:preview('Historic discoveries will be connected to dated sources and modern geography.','Example research card: discovery date, original report, regional context, and a source locator.'),
  conditions:preview('Weather and river conditions need live providers, checked observation times, and clear coverage limits.','Example display: station name · observation time · flow trend · forecast source. No live readings are shown.'),
  regulations:preview('A planned reference desk for land-manager rules, equipment restrictions, and access evidence.','Before a trip: identify the land manager, check claims and equipment rules, and confirm permission. No permission is inferred here.'),
  trail:`<ol class="dashboard-lesson-list">${result.lessons.slice(0,3).map((x,i)=>`<li><span>${i+1}</span><div><strong>${h(get(x.id)?.title)}</strong><small>${h(x.reasons[0]||'A published lesson from your learning sequence.')}</small></div></li>`).join('')||'<li>No unfinished lessons remain in the current sequence.</li>'}</ol>${note('Your profile and recorded completions shape this order. Use Recommended Articles to read and track lessons.')}`,
  articles:render(result.lessons,3)||'<p>No unfinished matching articles are available. Completed lessons remain in your passport.</p>',
  videos:render(result.videos)||'<p>No verified video resources are indexed for your current trail. We won’t substitute invented videos or timestamps.</p>',
  creators:existing(favorite,'No favorite creators selected or saved yet.')+(favorite.length?'':render(result.creators,2))+(!demo?'<a href="/compass/profile/?step=7">Choose favorite creators</a>':note('Example interests select real creator catalog entries; specific teaching claims may still be under review.')),
  bookshelf:preview('A future shelf for properly sourced books, PDFs, reading notes, and page references.','Example shelf sections: geology references · panning techniques · mining history. No book downloads are supplied.'),
  glossary:'<p>Look up panning, geology, and river terms in the existing searchable glossary. Definitions can be opened on hover, focus, or tap.</p><div class="dashboard-word-chip">placer</div><div class="dashboard-word-chip">sluice</div><div class="dashboard-word-chip">classifier</div><p><a href="/glossary/">Open the glossary →</a></p>',
  guide:demo?'<p>The existing Old Timer can match questions to real library resources. Optional AI requires configured credentials and member consent.</p>'+note('This example does not call an AI service or submit a question.'):`<p>Ask from your experience level and equipment. Library matching works without an AI provider; configured AI is optional and requires your consent.</p>${form(csrf,'/compass/guide/','<label class="compass-field">Your question<textarea name="question" maxlength="1000" required placeholder="What should I learn next?"></textarea></label>','Ask the Old Timer','data-chart-form')}`,
  achievements:`<div class="dashboard-stamps">${stamps.map(s=>`<div class="dashboard-stamp ${s.earned?'earned':''}"><span aria-hidden="true">${s.earned?'✦':'◇'}</span><strong>${h(s.name)}</strong><small>${s.earned?'Earned':'Not earned yet'}</small></div>`).join('')}</div>${demo?note('Illustrative stamps from this sample profile.'): '<a href="/compass/passport/">Open my Gold Trail Passport</a>'}`,
  shed:`<div class="dashboard-gear-tags">${owned.map(k=>`<span>${h(equipment[k])}</span>`).join('')||'<p>No equipment recorded yet.</p>'}</div>${state.inventory.length?`<ul>${state.inventory.slice(0,4).map(i=>`<li>${h(equipment[i.category])} · ${h(i.manufacturer||'Brand not entered')} ${h(i.model||'')} × ${h(i.quantity)}</li>`).join('')}</ul>`:''}${demo?note('Sample equipment categories; no private inventory loaded.'):'<a href="/compass/passport/">Manage manufacturers, models &amp; quantities →</a>'}`,
  wishlist:existing(savedRecords('product'),'No saved equipment yet. Use Save on a recommended product to add it to this list.'),
  comparison:preview('A planned side-by-side view of catalog specifications, useful differences, and source freshness.','Compare fit for your technique, portability, required extras, and available source-backed specifications.'),
  gear:render(result.products)||'<p>No extra purchases are recommended from this profile. Keep using the equipment you own.</p>',
  maintenance:preview('A future place for care notes, servicing dates, and manufacturer guidance.','Example note categories: clean and dry equipment · inspect hoses and fittings · record replacement parts.'),
  planner:preview('Build a future trip around confirmed access, travel preferences, and an equipment checklist.','Sample day outline: review access → prepare equipment → compare consistent samples → clean up and record observations.'),
  calendar:preview('A personal calendar for planned outings, reminders, and confirmed events.','Sample calendar entries: weekend equipment check · library reading session · trip planning. These are not real bookings.'),
  packing:`<p>A small interactive sample checklist. Your ticks last only while this page stays open.</p><fieldset class="dashboard-packing"><legend>Example river-day kit</legend>${['Pan and classifier','Snuffer bottle and sample containers','Water, food, and suitable clothing','Confirmed access details','Waste bag and a plan to get home'].map(t=>`<label><input type="checkbox"><span>${h(t)}</span></label>`).join('')}</fieldset>${note('Demonstration only · not a complete safety checklist or a saved packing plan.')}`,
  journal:preview('A future field notebook for observations and source-linked reflections. Sensitive entries will need a separate storage decision.','Illustrative entry outline: technique tried · sample conditions · what changed · questions for the next visit.'),
  finds:preview('A future optional discovery record. No amounts, private discoveries, or coordinates are collected by this preview.','Illustrative record headings: date · method · observations · optional discovery details. No input form is enabled.'),
  photos:preview('A future gallery with explicit privacy choices and a plan for image location metadata.','Example organization: equipment photos · educational close-ups · trip albums. No uploads are enabled.'),
  trips:preview('A future history of outings and lessons carried forward.','Illustrative summary: purpose of outing · techniques practiced · lesson learned. No trips have been inferred from your profile.'),
  discussions:preview('A future campfire for members to exchange practical questions and carefully sourced answers.','Example discussion prompts: keeping test pans comparable; choosing a classifier; what makes a useful field note.'),
  reports:preview('A future collection of member-submitted field reports with moderation and privacy controls.','Example report outline: broad region · method · observations · sources and access context. No member report is published here.'),
  followed:preview('A future feed for regions you choose to follow. It will not imply you visited them or disclose a private spot.','Example follow preference: broad region and topics of interest, with the option to stop following.'),
  updates:preview('A planned feed of verified public updates from saved creators.','Example update card: creator · video title · publication date · original source. No new video is invented or scraped here.'),
  vault:'<div class="dashboard-vault" aria-hidden="true">▣</div><h3>A private trail, thoughtfully planned.</h3><p>A future optional vault for sensitive field records. <strong>Zero-knowledge encryption is not implemented.</strong> This preview cannot accept GPS coordinates, discoveries, photographs, or notes.</p>'+note('No vault data is collected. Its storage design and security review belong to a separate phase.'),
  privacy:'<p>Your Compass answers, inventory, and activity stay associated with your authenticated account. They are not public. Ordinary database storage is not a zero-knowledge vault.</p>'+(demo?note('No member data is loaded in this example.'):'<a href="/compass/privacy/">Review AI consent &amp; private-data controls →</a>'),
  account:demo?'<p>Signed-in members can export their Compass data, delete Compass data, and view their existing account. Account closure and billing controls are not implemented here.</p>':`<p>Download your existing Compass records or manage profile deletion through its privacy page. Account closure and billing controls are not implemented here.</p>${form(csrf,'/compass/export/','','Export my Compass data')}<p><a href="/account/">View my account</a></p>`
 };
 const settings=Object.entries(dashboardGroups).map(([group,title])=>`<details class="dashboard-settings-group"><summary>${h(title)}</summary>${dashboardModules.filter(m=>m.group===group).map(m=>`<div class="dashboard-setting"><label><input type="checkbox" name="visible_${m.id}" value="yes"${layout.hidden.includes(m.id)?'':' checked'}><span>${h(m.title)} <small>${m.status==='working'?'Connected':m.status==='demo'?'Sample':'Preview'}</small></span></label><label class="dashboard-position">Position<select name="position_${m.id}" aria-label="Position of ${h(m.title)}">${layout.order.map((_,i)=>`<option value="${i+1}"${layout.order.indexOf(m.id)===i?' selected':''}>${i+1}</option>`).join('')}</select></label></div>`).join('')}</details>`).join('');
 const welcome=demo?'Welcome to your trail, Example Prospector.':`Welcome to your trail, ${h(member.display_name||member.username)}.`;
 return `<div class="member-dashboard" data-member-dashboard data-demo="${demo}" data-default-order="${dashboardModules.map(m=>m.id).join(',')}" data-default-visible="${defaultVisible.join(',')}">
 ${demo?`<section class="dashboard-demo-banner"><strong>Dashboard prototype · example data</strong><p>No member account or private data is loaded. Layout choices stay in this browser; sample progress is illustrative. Links open real site resources.</p><nav aria-label="Example prospecting profiles"><a href="/compass/demo/?persona=river"${persona==='river'?' aria-current="page"':''}>New England panner</a><a href="/compass/demo/?persona=detecting"${persona==='detecting'?' aria-current="page"':''}>Experienced gold detectorist</a></nav></section>`:''}
 ${reveal?'<p class="compass-success" role="status">Your profile is saved and your recommendations are ready.</p>':''}${saved?'<p class="compass-success" role="status">Your dashboard layout is saved to your account.</p>':''}
 <section class="dashboard-welcome"><div class="dashboard-compass" aria-hidden="true"><span>N</span><b>✦</b><small>GOLD TRAILS</small></div><div><span class="eyebrow">YOUR PERSONAL PROSPECTING HEADQUARTERS</span><h2>${welcome}</h2><p>${h(result.persona)} · ${h(experience[state.answers.experience]||'Experience not entered')}</p><div class="dashboard-profile-tags"><span>⌖ ${h(state.answers.region||'Region not entered')}</span><span>${h(goals[state.answers.goal]||'Your own pace, your own trail')}</span></div><p class="dashboard-profile-interests">${h((state.answers.interests||[]).map(k=>interests[k]).filter(Boolean).join(' · '))}</p>${demo?'':`<a href="/compass/profile/?step=0">Edit my prospecting profile</a> · <a href="/compass/profile/?step=7">Fine-tune preferences</a>`}</div></section>
 ${!demo&&!state.completedAt?`<p class="dashboard-demo-banner">Your profile is waiting. <a href="/compass/profile/?step=${state.step}">Continue onboarding</a> whenever you’re ready.</p>`:''}
 <div class="dashboard-toolbar"><div><span class="eyebrow">MAKE ROOM FOR YOUR KIND OF ADVENTURE</span><h2>Your field desk</h2><p>Connected tools use the existing site. Sample and preview cards show the next possibilities.</p></div><a class="outline-button" href="#dashboard-customize">Customize my desk</a></div>
 <details id="dashboard-customize" class="dashboard-customize"><summary>Arrange, hide, and restore modules</summary><p>${demo?'Example layout preferences are stored in this browser only.':'Layout preferences save to your account when you choose Save layout. Other profile answers and learning history are preserved.'} Use positions and visibility below, or the move controls on each card.</p><noscript><p>Choose positions and visibility, then Save layout. ${demo?'This example needs JavaScript to remember layout preferences.':''}</p></noscript>
 <form method="post" action="${demo?'/compass/demo/':'/compass/layout/'}" data-layout-form>${demo?'':hidden('csrf',csrf)}${hidden('revision',state.revision)}${settings}<div class="dashboard-settings-actions"><button class="gold-button" name="intent" value="save"${demo?' data-demo-action="save" disabled':''}>Save layout</button><button class="outline-button" name="intent" value="defaults"${demo?' data-demo-action="defaults" disabled':''}>Restore default desk</button><button class="outline-button" type="button" data-show-all hidden>Show every module</button></div></form></details>
 <p class="dashboard-layout-status" role="status" aria-live="polite" data-layout-status></p>
 <div class="dashboard-module-grid">${layout.order.map(id=>{const m=dashboardModules.find(m=>m.id===id);return `<section class="dashboard-module${id==='next'?' dashboard-module-wide':''}" data-module="${id}" data-group="${m.group}"${layout.hidden.includes(id)?' hidden':''} aria-labelledby="module-title-${id}"><header><span class="dashboard-module-icon" aria-hidden="true">${h(m.icon)}</span><div><span class="dashboard-state ${m.status}">${m.status==='working'?(demo?'Connected · example profile':'Connected'):m.status==='demo'?'Interactive sample':'Future preview'}</span><h2 id="module-title-${id}">${h(m.title)}</h2></div></header><div class="dashboard-module-body">${content[id]}</div><div class="dashboard-move-controls" hidden><button type="button" data-move="up" aria-label="Move ${h(m.title)} earlier">↑ <span>Earlier</span></button><button type="button" data-move="down" aria-label="Move ${h(m.title)} later">↓ <span>Later</span></button><button type="button" data-hide aria-label="Hide ${h(m.title)}">Hide</button></div></section>`;}).join('')}</div>
 ${demo?'<p class="dashboard-endnote">Explore this example, then <a href="/login/">sign in to your Gold Trails account</a>. Premium access still follows the existing membership checks.</p>':`<details class="dashboard-tuning"><summary>Recommendation controls</summary><div class="compass-actions">${form(csrf,'/compass/refresh/','','Refresh recommendations')}${form(csrf,'/compass/reset/','<p>Reset dismissed items and tuning. Saves and completed lessons stay.</p>','Reset recommendation preferences')}</div></details>`}
 </div>`;
}
