import {createHash,randomUUID} from 'node:crypto';
import {creatorCatalog} from './creator-catalog.js';
import {safeUrl} from './directory-views.js';
export class CatalogConflict extends Error {}
export function channelKey(value){const valid=safeUrl(value);if(!valid)return null;const u=new URL(valid);let host=u.hostname.toLowerCase().replace(/^www\./,'');let path=u.pathname.replace(/\/+$/,'');if(['youtube.com','m.youtube.com'].includes(host)){host='youtube.com';path=path.replace(/\/(videos|featured|about|streams)$/i,'').toLowerCase();if(path!=='/watch')u.search='';}return host+path+u.search;}
function validate(rows){const slugs=new Set(),links=new Set();for(const p of rows){if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p.slug)||p.slug.length>160||!p.name||p.name.length>180||!['lead','verified','published'].includes(p.status)||!channelKey(p.official_url)||p.region_source&&!safeUrl(p.region_source)||p.region&&p.region.length>180||!/^\d{4}-\d{2}-\d{2}$/.test(p.checked_at))throw new CatalogConflict('Invalid roster entry');if(slugs.has(p.slug)||links.has(channelKey(p.official_url)))throw new CatalogConflict('Duplicate roster entry');slugs.add(p.slug);links.add(channelKey(p.official_url));}}
export function planCatalog(rows,people,channels){validate(rows);const entries=rows.map(p=>{const existing=people.find(x=>x.slug===p.slug);if(existing)return {...p,action:'preserve',reason:existing.archived_at?'Existing archived profile preserved':'Existing profile preserved'};const duplicate=channels.find(c=>channelKey(c.canonical_url)===channelKey(p.official_url));if(duplicate)return {...p,action:'conflict',reason:'This channel already belongs to another profile'};return {...p,action:'add',reason:p.status==='lead'?'Research lead; facts remain under review':'Basic research profile'};});const digest=createHash('sha256').update(JSON.stringify({rows,people,channels})).digest('hex');return {digest,entries,add:entries.filter(p=>p.action==='add').length,preserve:entries.filter(p=>p.action==='preserve').length,conflicts:entries.filter(p=>p.action==='conflict').length};}
async function snapshot(query,lock=false){const people=await query('SELECT id,slug,publication_status,archived_at,edit_version FROM people ORDER BY slug'+(lock?' FOR UPDATE':''));const channels=await query('SELECT id,person_id,canonical_url,archived_at FROM channels ORDER BY id'+(lock?' FOR UPDATE':''));return {people,channels};}
export async function previewCatalog(db,rows=creatorCatalog()){const data=await snapshot(sql=>db.query(sql));return planCatalog(rows,data.people,data.channels);}
export async function importCatalog(db,{expectedDigest,visibility='published',actor,rows=creatorCatalog()}){
 if(!/^[a-f0-9]{64}$/.test(expectedDigest||'')||!['published','draft'].includes(visibility)||!actor||actor.length>180)throw new CatalogConflict('Invalid import request');
 const conn=await db.getConnection();
 try{await conn.beginTransaction();const data=await snapshot(sql=>conn.query(sql),true);const plan=planCatalog(rows,data.people,data.channels);if(plan.digest!==expectedDigest)throw new CatalogConflict('Roster or database changed; reload the import preview');
 const formats=await conn.query("SELECT id,code FROM formats WHERE code IN ('article','video') AND archived_at IS NULL");if(!formats.some(f=>f.code==='article'))throw new CatalogConflict('Article source format is unavailable');
 const role=await conn.query("SELECT id FROM public_roles WHERE code='creator' AND archived_at IS NULL");
 const regions=await conn.query('SELECT id,slug,name,publication_status,archived_at FROM regions ORDER BY id FOR UPDATE');let created=0;const conflicts=[];
 for(const p of plan.entries){if(p.action==='conflict'){conflicts.push(p.slug);continue;}if(p.action!=='add')continue;
 let regionId=null;if(p.region){const match=regions.find(r=>r.name.toLowerCase()===p.region.toLowerCase());if(match&&!match.archived_at&&match.publication_status==='published')regionId=match.id;else if(!match){const slug='coverage-'+createHash('sha256').update(p.region).digest('hex').slice(0,24);if(regions.some(r=>r.slug===slug))throw new CatalogConflict('Region identity conflict');regionId=randomUUID();await conn.query("INSERT INTO regions(id,slug,name,region_type,description,publication_status) VALUES(?,?,?,'area',?,'published')",[regionId,slug,p.region,'Broad creator coverage from the research roster; not a prospecting access location.']);regions.push({id:regionId,slug,name:p.region,publication_status:'published',archived_at:null});}}
 const id=randomUUID(),channelId=randomUUID(),resourceId=randomUUID(),referenceId=randomUUID();const lead=p.status==='lead';const introduction=lead?'Creator research lead; channel details are under review.':'Prospecting creator in the Gold Trails research roster.';const bio=lead?'This channel is included as a research lead. The creator’s background, techniques, and locations remain to be verified.':'This creator is included in the Gold Trails research roster. Additional biographical details and resources remain under review.';
 await conn.query("INSERT INTO people(id,slug,display_name,short_introduction,biography,primary_region_id,publication_status,verification_status) VALUES(?,?,?,?,?,?,?,'unverified')",[id,p.slug,p.name,introduction,bio,regionId,visibility]);
 const sourceUrl=new URL(p.official_url);const isVideo=sourceUrl.hostname.match(/(^|\.)youtube\.com$/i)&&sourceUrl.pathname==='/watch';
 const platform=sourceUrl.hostname.match(/(^|\.)youtube\.com$/i)?'YouTube':'website';
 if(!isVideo)await conn.query("INSERT INTO channels(id,person_id,platform,channel_name,canonical_url,publication_status) VALUES(?,?,?,?,?,?)",[channelId,id,platform,p.name,p.official_url,visibility]);
 await conn.query("INSERT INTO resources(id,slug,title,canonical_url,format_id,publication_status) VALUES(?,?,?,?,?,?)",[resourceId,'creator-source-'+resourceId,p.name+' — public source',p.official_url,(formats.find(f=>f.code===(isVideo?'video':'article'))||formats.find(f=>f.code==='article')).id,visibility]);
 await conn.query('INSERT INTO source_references(id,resource_id,evidence_note,accessed_at) VALUES(?,?,?,?)',[referenceId,resourceId,'Imported public source link from the research roster. Preserves creator attribution only; biography, experience and location are not verified by this import.',p.checked_at+' 00:00:00']);
 await conn.query("INSERT INTO person_fact_sources(id,person_id,field_key,source_reference_id,assessment,reviewer_note) VALUES(?,?,'display_name',?,'supports',?)",[randomUUID(),id,referenceId,'Creator attribution from the research roster; biography and region remain under review.']);
 if(!isVideo)await conn.query("INSERT INTO channel_fact_sources(id,channel_id,field_key,source_reference_id,assessment) VALUES(?,?,'canonical_url',?,'supports')",[randomUUID(),channelId,referenceId]);
 if(regionId)await conn.query("INSERT INTO person_regions(person_id,region_id,relationship_type) VALUES(?,?,'covers')",[id,regionId]);
 if(regionId&&p.region_source){const coverageResource=randomUUID(),coverageRef=randomUUID();await conn.query("INSERT INTO resources(id,slug,title,canonical_url,format_id,publication_status) VALUES(?,?,?,?,?,?)",[coverageResource,'creator-source-'+coverageResource,p.name+' — coverage source',p.region_source,formats.find(f=>f.code==='article').id,visibility]);await conn.query('INSERT INTO source_references(id,resource_id,evidence_note,accessed_at) VALUES(?,?,?,?)',[coverageRef,coverageResource,'Creator-stated broad prospecting coverage. Does not establish residence, access permission or experience.',p.checked_at+' 00:00:00']);await conn.query("INSERT INTO person_fact_sources(id,person_id,field_key,source_reference_id,assessment,reviewer_note) VALUES(?,?,'primary_region_id',?,'supports',?)",[randomUUID(),id,coverageRef,'Broad coverage only.']);}

 if(role.length)await conn.query('INSERT INTO person_public_roles(person_id,role_id) VALUES(?,?)',[id,role[0].id]);
 await conn.query("INSERT INTO creator_change_log(id,person_id,actor,action) VALUES(?,?,?,'create')",[randomUUID(),id,actor]);created++;
 }
 await conn.commit();return {created,preserved:plan.preserve,conflicts};
 }catch(error){await conn.rollback();throw error;}finally{conn.release();}
}

// Fixed creator-domain allowlist excludes members, passwords, sessions and billing.
export const creatorBackupTables=['people','channels','regions','public_roles','languages','audience_levels','formats','topics','resources','source_references','person_aliases','person_public_roles','person_languages','person_audience_levels','person_formats','person_regions','person_topics','resource_people','person_featured_resources','public_contacts','person_fact_sources','channel_fact_sources','creator_change_log'];
export async function backupCreators(db){const conn=await db.getConnection();try{await conn.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');await conn.beginTransaction();const tables={};for(const name of creatorBackupTables)tables[name]=await conn.query('SELECT * FROM '+name);const versions=await conn.query('SELECT version FROM schema_migrations');if(versions.some(v=>v.version==='003_creator_associates'))tables.creator_associates=await conn.query('SELECT * FROM creator_associates');if(versions.some(v=>v.version==='005_creator_research'))for(const name of ['creator_profile_claims','creator_channel_identities','waterways','creator_waterway_evidence','creator_research_conflicts'])tables[name]=await conn.query('SELECT * FROM '+name);if(versions.some(v=>v.version==='008_business_contact_research'))tables.business_contact_research=await conn.query('SELECT * FROM business_contact_research');await conn.commit();return {format:'gold-trails-creator-backup-v1',created_at:new Date().toISOString(),schema_versions:versions.map(v=>v.version),tables};}catch(error){await conn.rollback();throw error;}finally{conn.release();}}
