import {safeUrl} from './directory-views.js';
import {regionKey} from '../dist/prospectors-data.js';
// Display anchors are broad region centers, never creator addresses or prospecting sites.
const anchors={ 'new england':[44,-71], 'midwestern usa':[42,-90], 'southern australia':[-35,138], 'western australia':[-25,122], 'nsw':[-32,147], 'new zealand':[-42,173], 'ariège':[43,1.6], 'wales':[52,-4], 'scotland':[57,-4], 'united kingdom':[54,-2], 'australia':[-25,134], 'vancouver island':[49.7,-125.5], 'pacific northwest':[46,-122], 'maine':[45,-69], 'new hampshire':[44,-71.5], 'vermont':[44,-72.7], 'massachusetts':[42.3,-71.8], 'new york':[43,-75], 'pennsylvania':[41,-77.5], 'virginia':[37.5,-79], 'north carolina':[35.6,-79.8], 'south carolina':[34,-81], 'georgia':[32.6,-83.4], 'florida':[28,-82], 'alabama':[32.8,-86.8], 'tennessee':[36,-86], 'kentucky':[37.5,-85.3], 'ohio':[40,-82.8], 'michigan':[44,-85], 'wisconsin':[44.5,-89.5], 'minnesota':[46,-94], 'illinois':[40,-89], 'indiana':[40,-86], 'iowa':[42,-93.5], 'missouri':[38.5,-92.5], 'arkansas':[35,-92.5], 'louisiana':[31,-92], 'mississippi':[33,-90], 'texas':[31,-99], 'oklahoma':[35.5,-97.5], 'kansas':[38.5,-98], 'nebraska':[41.5,-99.5], 'south dakota':[44.5,-100], 'north dakota':[47.5,-100.5], 'montana':[47,-110], 'wyoming':[43,-107.5], 'colorado':[39,-105.5], 'new mexico':[34.5,-106], 'arizona':[34.5,-112], 'utah':[39.5,-111.5], 'nevada':[39,-117], 'california':[37,-120], 'oregon':[44,-120.5], 'washington':[47.5,-120.5], 'idaho':[44.5,-114.5], 'alaska':[64,-153], 'hawaii':[20.5,-157], 'delaware':[39,-75.5], 'maryland':[39,-76.7], 'connecticut':[41.6,-72.7], 'rhode island':[41.7,-71.5], 'new jersey':[40,-74.5], 'west virginia':[39,-80.5], 'british columbia':[54,-125], 'alberta':[54,-115], 'saskatchewan':[54,-106], 'manitoba':[54,-98], 'ontario':[50,-85], 'quebec':[52,-71], 'new brunswick':[46.5,-66.5], 'nova scotia':[45,-63], 'yukon':[64,-136], 'northwest territories':[65,-120], 'nunavut':[67,-95], 'newfoundland and labrador':[54,-60], 'prince edward island':[46.5,-63] };
export function regionAnchor(name){const text=String(name||'').toLowerCase();const key=Object.keys(anchors).sort((a,b)=>b.length-a.length).find(k=>new RegExp('(^|[^a-z])'+k+'([^a-z]|$)').test(text));return key?{label:key.split(' ').map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(' ').replace('Usa','USA').replace('Nsw','NSW'),lat:anchors[key][0],lng:anchors[key][1]}:null;}
export function settingsFor(topics){const text=topics.map(t=>t.name.toLowerCase());const out=[];if(text.some(t=>/river|stream|creek/.test(t)))out.push('river');if(text.some(t=>/desert|drywashing|dry washing|metal detecting/.test(t)))out.push('ground');if(text.some(t=>/hard.?rock|tailings|mine sites|strip min/.test(t)))out.push('mine');return out;}
const coverageAnchors=name=>[...new Map([name,...String(name).split(/;|\s+(?:and|&)\s+/i)].map(regionAnchor).filter(Boolean).map(r=>[r.label,r])).values()];
export function mapRecords(people,regions,topics){return people.map(p=>{
 const coverage=regions.filter(r=>r.person_id===p.id),connections=topics.filter(t=>t.person_id===p.id);
 const location=coverage.map(r=>r.name).join(' · ')||p.primary_region||'';
 const mapped=[...new Map(coverage.flatMap(r=>coverageAnchors(r.name)).map(r=>[r.label,r])).values()];
 const regionOptions=coverage.flatMap(r=>{const anchors=coverageAnchors(r.name);return anchors.length?anchors.map(anchor=>({slug:regionKey(anchor.label),name:anchor.label})):[{slug:r.slug||regionKey(r.name),name:r.name}];});
 return {slug:p.slug,profileUrl:safeUrl(p.profile_url),name:p.display_name,location,
  introduction:p.short_introduction||'',searchText:[p.nickname,p.biography,p.state_province,p.country_code,p.search_aliases].filter(Boolean).join(' '),
  topics:connections.filter(t=>!t.is_specialty).map(t=>({slug:t.slug||regionKey(t.name),name:t.name})),
  specialties:connections.filter(t=>t.is_specialty).map(t=>t.slug),
  regionOptions,regionKeys:[...new Set(coverage.flatMap(r=>[r.slug,regionKey(r.name),...coverageAnchors(r.name).map(a=>regionKey(a.label))]).filter(Boolean))],
  settings:settingsFor(connections.filter(t=>t.relationship_type!=='equipment_discussed'&&!t.is_specialty)),
  regions:mapped};
 });}
