import {timingSafeEqual} from 'node:crypto';
import {token,digest,hashPassword,verifyPassword} from './admin-auth.js';
import {page,escapeHtml as h} from './directory-views.js';
const routes=new Set(['/login/','/signup/','/account/','/logout/','/forgot-password/','/reset-password/','/verify-email/','/resend-verification/']);
const cookie=(name,value,age=28800)=>`__Host-gold-${name}=${value}; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=${age}`;
const read=(req,name)=>(req.headers.cookie||'').match(new RegExp(`(?:^|;\\s*)__Host-gold-${name}=([a-f0-9]{64})(?:;|$)`))?.[1]||null;
const equal=(a,b)=>/^[a-f0-9]{64}$/.test(a||'')&&/^[a-f0-9]{64}$/.test(b||'')&&timingSafeEqual(Buffer.from(a),Buffer.from(b));
class InputError extends Error{}
export function memberIdentity(f){const username=(f.get('username')||'').trim(),email=(f.get('email')||'').trim().toLowerCase(),displayName=(f.get('displayName')||'').trim()||null,password=f.get('password')||'';if(!/^[a-z0-9_-]{3,40}$/i.test(username)||['admin','administrator','support','goldtrails','root'].includes(username.toLowerCase()))throw new InputError('Choose a username of 3–40 letters, numbers, underscores or hyphens.');if(!validEmail(email))throw new InputError('Enter a valid email address.');if(displayName&&displayName.length>180)throw new InputError('Keep your display name under 180 characters.');passwordInput(f);return{username,email,displayName,password};}
const validEmail=e=>e.length<=254&&/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(e);
function passwordInput(f){const p=f.get('password')||'';if(p.length<8||p.length>128)throw new InputError('Use a password of 8–128 characters.');if(f.has('confirmPassword')&&p!==f.get('confirmPassword'))throw new InputError('The two passwords do not match.');return p;}
async function body(req){if(!/^application\/x-www-form-urlencoded(?:;|$)/i.test(req.headers['content-type']||''))throw new InputError('Unsupported form.');let n=0,b=[];for await(const c of req){n+=c.length;if(n>8192)throw new InputError('Form too large.');b.push(c);}const f=new URLSearchParams(Buffer.concat(b).toString('utf8')),seen=new Set();for(const k of f.keys()){if(seen.has(k))throw new InputError('Duplicate field.');seen.add(k);}return f;}
const hidden=(k,v)=>`<input type="hidden" name="${k}" value="${h(v)}">`;
const input=(name,label,type='text',auto='')=>`<label>${label}<input id="member-${name}" name="${name}" type="${type}" ${auto?`autocomplete="${auto}"`:''} ${type==='password'?`minlength="8" maxlength="128" ${auto==='new-password'?'aria-describedby="password-guidance" passwordrules="minlength: 8; maxlength: 128;"':''}`:name==='username'?'minlength="3" maxlength="40" pattern="[a-zA-Z0-9_-]{3,40}"':'maxlength="254"'} required></label>`;
const passwords=()=>'<p id="password-guidance" class="member-form-guidance">Use 8–128 characters. Enter your password once; you can show it below to check it.</p>'+input('password','Password','password','new-password')+'<div class="member-password-controls"><button type="button" class="member-password-toggle" data-password-toggle aria-controls="member-password" aria-pressed="false" hidden>Show password</button></div>';
const shell=(title,body)=>page(title,'Your Gold Trails membership',`<section class="resource-placeholder member-card"><h2>${h(title)}</h2>${body}</section>`,`<section class="panel related"><h2>Your camp</h2><a href="/">Gold Trails home</a><a href="/prospectors/">Creator directory</a><a href="/signup/">Free membership</a><a href="/login/">Member sign-in</a><a href="/admin/login/">Administrator sign-in</a></section>`,'A home for your curiosity.').replace('class="category-page"','class="category-page member-page"').replace('GOLD TRAILS / PROSPECTOR DIRECTORY','THE MEMBERS’ LODGE').replace(/ aria-current="(?:location|page)"/g,'').replace(/<nav class="breadcrumb"[^>]*>.*?<\/nav>/,`<nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><span aria-current="page">${h(title)}</span></nav>`);
const form=(path,csrf,content,button)=>`<form ${path==='/signup/'?'data-async-signup':''} class="admin-form member-form" method="post" action="${path}">${hidden('csrf',csrf)}${content}<p class="member-form-feedback" role="status" aria-live="polite" aria-atomic="true" hidden></p><button type="submit" class="gold-button">${h(button)}</button></form>`;
export function memberConfig(env=process.env){try{const raw=env.MEMBER_ORIGIN||env.ADMIN_ORIGIN;if(!raw)return null;const u=new URL(raw);return u.protocol==='https:'&&u.origin===raw&&!u.username&&!u.password?{origin:raw,open:env.MEMBER_SIGNUP_ENABLED==='true'}:null;}catch{return null;}}
export function createMemberHandler({store=null,config=null,mail=null,log=console.error}){
 return async(req,res,url)=>{
  if(routes.has(url.pathname+'/')){res.writeHead(308,{Location:url.pathname+'/'+url.search,'Cache-Control':'no-store'});res.end();return true;}
  if(!routes.has(url.pathname))return false;
  let csrf=read(req,'form')||token(),newCookie=!read(req,'form');const raw=read(req,'member');
  const send=(status,title,content,extra={})=>{const json=url.pathname==='/signup/'&&req.method==='POST'&&req.headers.accept==='application/json';res.writeHead(status,{'Content-Type':json?'application/json; charset=utf-8':'text/html; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; img-src 'self' data:; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self'; frame-ancestors 'none'; form-action 'self'; base-uri 'none'",...(newCookie?{'Set-Cookie':cookie('form',csrf)}:{}),...extra});res.end(req.method==='HEAD'?undefined:json?JSON.stringify({outcome:status===200&&title==='Check your email'?'email_requested':'error',title,message:(content.match(/<p\b[^>]*>([\s\S]*?)<\/p>/)?.[1]||content).replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim()}):shell(title,content).replace('</body>','<script src="/member-forms.js?v=3" defer></script></body>'));};
  const redirect=(path,cookies)=>send(303,'Continue','',{'Location':path,...(cookies?{'Set-Cookie':cookies}:{})});
  const emailLink=async(p,purpose)=>{const raw=await store.issue(p.id,purpose);await mail({to:p.email,purpose,url:`${config.origin}/${purpose==='verify_email'?'verify-email':'reset-password'}/?token=${raw}`});};
  try{
   if(!['GET','HEAD','POST'].includes(req.method)){send(405,'Use the form','<p>That action is unavailable.</p>',{Allow:'GET, HEAD, POST'});return true;}
   const ready=store&&config&&await store.ready(),open=ready&&config.open&&Boolean(mail);let f;
   if(req.method==='POST'){if(!ready){send(503,'Members coming soon','<p>Member access is being prepared.</p>');return true;}if(req.headers.origin!==config.origin){send(403,'Form expired','<p>Return to the page and try again.</p>');return true;}f=await body(req);if(!equal(read(req,'form'),f.get('csrf'))){send(403,'Form expired','<p>Refresh the form and try again.</p>');return true;}}
   if(url.pathname==='/signup/'){
    if(!open){send(200,'Join the camp',`<p>Create a free account to join Gold Trails. Registration opens when email verification is ready.</p><div class="member-plans"><div><h3>Free membership</h3><p>Your own account, with more features coming as the library grows.</p><strong>Free to join</strong></div><div><h3>Subscriber membership</h3><p>Additional benefits and pricing are being planned.</p><strong>Coming later</strong></div></div><fieldset disabled class="member-preview"><legend>Signup preview</legend>${form('/signup/',csrf,input('username','Username','text','username')+input('email','Email','email','email')+passwords(),'Create free account')}</fieldset><p>Already a member? <a href="/login/">Sign in</a>.</p>`);return true;}
    if(req.method==='POST'){if(!await store.allow('signup')){send(429,'Take a short break','<p>Please try again in 15 minutes.</p>');return true;}const data=memberIdentity(f);let p;try{p=await store.signup({...data,passwordHash:await hashPassword(data.password,{minLength:8})});}catch(e){if(e.code!=='ER_DUP_ENTRY')throw e;}if(p)await emailLink(p,'verify_email');send(200,'Check your email','<div class="member-confirmation" role="status"><h3>Your signup request was received</h3><p>If these details could be registered, a verification link is on its way. Check your inbox and spam folder, then follow the link to activate your account.</p></div><p>No email after a few minutes? <a href="/resend-verification/">Request another verification email</a>.</p><p><a href="/login/">Return to member sign-in</a></p>');return true;}
    send(200,'Join the camp',`<p>Start with free membership. Subscriber benefits will be introduced later.</p>${form('/signup/',csrf,input('username','Username','text','username')+input('email','Email','email','email')+'<label>Display name (optional)<input name="displayName" maxlength="180" autocomplete="nickname"></label>'+passwords(),'Create free account')}<p><a href="/login/">Already a member?</a></p>`);return true;
   }
   if(url.pathname==='/login/'){
    if(req.method==='POST'){if(!await store.allow('login')){send(429,'Take a short break','<p>Please try again in 15 minutes.</p>');return true;}const email=(f.get('email')||'').trim().toLowerCase(),password=f.get('password')||'';const p=validEmail(email)?await store.find(email):null;const dummy='scrypt:'+'0'.repeat(32)+':'+'0'.repeat(128);const ok=await verifyPassword(password,p?.password_hash||dummy);if(!p||!ok||p.status!=='active'||!p.email_verified_at){send(401,'Member sign-in','<p role="alert">Sign-in details were not recognized, or email verification is pending.</p>'+form('/login/',csrf,input('email','Email','email','email')+input('password','Password','password','current-password'),'Sign in')+'<a href="/forgot-password/">Reset password</a> · <a href="/resend-verification/">Verify email</a>');return true;}await store.logout(raw);csrf=token();const fresh=await store.login(p.id,p.auth_version,csrf);if(!fresh){send(401,'Sign in again','<p>Please try again.</p>');return true;}const membership=await store.session(fresh);redirect(membership?.effective_level==='subscriber'?'/compass/':'/account/',[cookie('form',csrf),cookie('member',fresh)]);return true;}
    send(200,'Member sign-in',form('/login/',csrf,input('email','Email','email','email')+input('password','Password','password','current-password'),'Sign in')+'<p><a href="/forgot-password/">Forgot your password?</a> · <a href="/signup/">Join free</a></p><p><a href="/admin/login/">Administrator sign-in</a></p>');return true;
   }
   if(url.pathname==='/account/'||url.pathname==='/logout/'){
    const p=ready?await store.session(raw):null;if(!p){redirect('/login/');return true;}if(url.pathname==='/logout/'){if(req.method!=='POST'){send(405,'Use the sign-out button','<p>Return to your account.</p>');return true;}if(!equal(digest(csrf),p.csrf_token_hash)){send(403,'Form expired','<p>Sign in again.</p>');return true;}await store.logout(raw);redirect('/login/',[cookie('member','',0),cookie('form','',0)]);return true;}
    if(req.method==='POST'){send(405,'Account overview','<p>Profile editing is coming later.</p>');return true;}
    send(200,'Your camp',`<p>Welcome, ${h(p.display_name||p.username)}.</p><dl class="profile-facts"><div><dt>Account number</dt><dd>GT-${h(String(p.account_number).padStart(6,'0'))}</dd></div><div><dt>Username</dt><dd>${h(p.username)}</dd></div><div><dt>Email</dt><dd>${h(p.email)}</dd></div><div><dt>Membership</dt><dd>${p.effective_level==='subscriber'?'Subscriber':'Free'}</dd></div></dl><p><a class="gold-button" href="/compass/">${p.effective_level==='subscriber'?'Open Gold Trails Compass':'Preview Gold Trails Compass'}</a></p><p>Payment checkout is still being prepared.</p>${form('/logout/',csrf,'','Sign out')}`);return true;
   }
   if(url.pathname==='/forgot-password/'||url.pathname==='/resend-verification/'){
    const verify=url.pathname==='/resend-verification/';if(req.method==='POST'){if(!mail){send(503,'Email service being prepared','<p>Please return when member email is ready.</p>');return true;}if(!await store.allow('recovery')){send(429,'Take a short break','<p>Please try again in 15 minutes.</p>');return true;}const email=(f.get('email')||'').trim().toLowerCase();if(!validEmail(email))throw new InputError('Enter a valid email address.');const p=await store.find(email);if(p&&p.status!=='suspended'&&(verify?!p.email_verified_at:Boolean(p.email_verified_at))){try{await emailLink(p,verify?'verify_email':'reset_password');}catch{log('Gold Trails member email unavailable');}}send(200,'Check your email','<p>If an eligible account exists, an email is on its way. Please check your inbox and spam folder.</p>');return true;}
    send(200,verify?'Verify your email':'Find your way back',mail?form(url.pathname,csrf,input('email','Email','email','email'),verify?'Send verification link':'Send reset link'):'<p>Email verification and password recovery will open when member email is configured.</p>');return true;
   }
   const verify=url.pathname==='/verify-email/',t=req.method==='POST'?f.get('token'):url.searchParams.get('token');if(!/^[a-f0-9]{64}$/.test(t||'')){send(400,'Link unavailable','<p>Use the complete email link, or request a new one.</p>');return true;}
   if(req.method==='POST'){if(!await store.allow('token')){send(429,'Take a short break','<p>Please try again in 15 minutes.</p>');return true;}const hash=verify?null:await hashPassword(passwordInput(f),{minLength:8});const ok=await store.consume(t,verify?'verify_email':'reset_password',hash);send(ok?200:400,ok?(verify?'Email verified':'Password updated'):'Link expired',ok?'<p>You can now <a href="/login/">sign in</a>.</p>':'<p>This link has expired or was already used. Request a new email.</p>');return true;}
   send(200,verify?'Confirm your email':'Choose a new password',form(url.pathname,csrf,hidden('token',t)+(verify?'<p>Confirm your email to activate your free account.</p>':passwords()),verify?'Verify email':'Update password'));return true;
  }catch(e){if(e instanceof InputError)send(400,'Check the form',`<p role="alert">${h(e.message)}</p><p>Use Back to correct your entries.</p>`);else{log('Gold Trails member request unavailable');send(503,'A pause at camp','<p role="alert">We could not finish this request. Your account may already have been created if the email service was interrupted.</p><p><a href="/resend-verification/">Request a verification email</a> or <a href="/signup/">return to signup</a>.</p>');}}return true;
 };
}
