import {randomUUID} from 'node:crypto';
import {digest,token} from './admin-auth.js';
export function createMemberStore(db){
 const tx=async fn=>{const c=await db.getConnection();try{await c.beginTransaction();const out=await fn(c);await c.commit();return out;}catch(e){await c.rollback();throw e;}finally{c.release();}};
 const audit=(c,id,action)=>c.query('INSERT INTO member_audit_log(id,account_id,action) VALUES(?,?,?)',[randomUUID(),id,action]);
 return {
 async ready(){return (await db.query("SELECT version FROM schema_migrations WHERE version='004_member_accounts'")).length>0;},
 async allow(action){const bucket=digest('member-'+action);await db.query(`INSERT INTO admin_login_limits(bucket,attempts,window_start) VALUES(?,1,UTC_TIMESTAMP(6)) ON DUPLICATE KEY UPDATE attempts=IF(window_start<DATE_SUB(UTC_TIMESTAMP(6),INTERVAL 15 MINUTE),1,attempts+1),window_start=IF(window_start<DATE_SUB(UTC_TIMESTAMP(6),INTERVAL 15 MINUTE),UTC_TIMESTAMP(6),window_start)`,[bucket]);return (await db.query('SELECT attempts FROM admin_login_limits WHERE bucket=?',[bucket]))[0].attempts<=({login:30,signup:10,recovery:10,token:30}[action]||10);},
 async find(email){return (await db.query('SELECT id,password_hash,status,email,email_verified_at,auth_version FROM member_accounts WHERE email=? AND archived_at IS NULL',[email]))[0]||null;},
 async signup({username,email,passwordHash,displayName}){return tx(async c=>{const id=randomUUID();await c.query('INSERT INTO member_accounts(id,username,email,password_hash) VALUES(?,?,?,?)',[id,username,email,passwordHash]);await c.query('INSERT INTO member_profiles(account_id,display_name) VALUES(?,?)',[id,displayName]);await c.query('INSERT INTO member_memberships(account_id) VALUES(?)',[id]);await c.query("INSERT INTO member_role_grants(account_id,role_code) VALUES(?,'member')",[id]);await audit(c,id,'signup');return{id,email};});},
 async issue(id,purpose){return tx(async c=>{await c.query('SELECT id FROM member_accounts WHERE id=? FOR UPDATE',[id]);await c.query('UPDATE member_tokens SET revoked_at=UTC_TIMESTAMP(6) WHERE account_id=? AND purpose=? AND consumed_at IS NULL AND revoked_at IS NULL',[id,purpose]);const raw=token();await c.query('INSERT INTO member_tokens(token_hash,purpose,account_id,expires_at) VALUES(?,?,?,DATE_ADD(UTC_TIMESTAMP(6),INTERVAL ? SECOND))',[digest(raw),purpose,id,purpose==='reset_password'?1800:86400]);return raw;});},
 async consume(raw,purpose,passwordHash=null){return tx(async c=>{const t=(await c.query('SELECT account_id FROM member_tokens WHERE token_hash=? AND purpose=? AND consumed_at IS NULL AND revoked_at IS NULL AND expires_at>UTC_TIMESTAMP(6)',[digest(raw),purpose]))[0];if(!t)return false;const p=(await c.query('SELECT status FROM member_accounts WHERE id=? AND archived_at IS NULL FOR UPDATE',[t.account_id]))[0];if(!p||p.status==='suspended')return false;const valid=(await c.query('SELECT token_hash FROM member_tokens WHERE token_hash=? AND purpose=? AND consumed_at IS NULL AND revoked_at IS NULL AND expires_at>UTC_TIMESTAMP(6) FOR UPDATE',[digest(raw),purpose]))[0];if(!valid)return false;if(purpose==='verify_email'){await c.query("UPDATE member_accounts SET email_verified_at=UTC_TIMESTAMP(6),status='active' WHERE id=?",[t.account_id]);}else{await c.query('UPDATE member_accounts SET password_hash=?,password_changed_at=UTC_TIMESTAMP(6),auth_version=auth_version+1 WHERE id=?',[passwordHash,t.account_id]);await c.query('UPDATE member_sessions SET revoked_at=UTC_TIMESTAMP(6) WHERE account_id=? AND revoked_at IS NULL',[t.account_id]);}await c.query('UPDATE member_tokens SET consumed_at=UTC_TIMESTAMP(6) WHERE token_hash=?',[digest(raw)]);await c.query('UPDATE member_tokens SET revoked_at=UTC_TIMESTAMP(6) WHERE account_id=? AND purpose=? AND token_hash<>? AND consumed_at IS NULL AND revoked_at IS NULL',[t.account_id,purpose,digest(raw)]);await audit(c,t.account_id,purpose);return true;});},
 async login(id,version,csrf){return tx(async c=>{const p=(await c.query("SELECT auth_version FROM member_accounts WHERE id=? AND status='active' AND email_verified_at IS NOT NULL AND archived_at IS NULL FOR UPDATE",[id]))[0];if(!p||p.auth_version!==version)return null;const raw=token();await c.query('INSERT INTO member_sessions(token_hash,account_id,csrf_token_hash,auth_version,expires_at) VALUES(?,?,?,?,DATE_ADD(UTC_TIMESTAMP(6),INTERVAL 8 HOUR))',[digest(raw),id,digest(csrf),version]);await c.query('UPDATE member_accounts SET last_login_at=UTC_TIMESTAMP(6) WHERE id=?',[id]);await audit(c,id,'login');return raw;});},
 async session(raw){if(!raw)return null;return (await db.query(`SELECT a.id,a.username,a.account_number,a.email,p.display_name,s.csrf_token_hash,m.level,m.status AS membership_status,m.grant_source,m.ends_at,m.starts_at,CASE WHEN m.level='subscriber' AND m.status='active' AND m.starts_at<=UTC_TIMESTAMP(6) AND (m.ends_at IS NULL OR m.ends_at>UTC_TIMESTAMP(6)) AND ((m.grant_source='complimentary' AND m.granted_by IS NOT NULL) OR (m.grant_source='payment' AND EXISTS(SELECT 1 FROM member_subscriptions sub WHERE sub.id=m.subscription_id AND sub.account_id=a.id AND sub.status IN ('active','trialing') AND sub.current_period_start<=UTC_TIMESTAMP(6) AND sub.current_period_end>UTC_TIMESTAMP(6)))) THEN 'subscriber' ELSE 'free' END AS effective_level FROM member_sessions s JOIN member_accounts a ON a.id=s.account_id LEFT JOIN member_profiles p ON p.account_id=a.id LEFT JOIN member_memberships m ON m.account_id=a.id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>UTC_TIMESTAMP(6) AND s.auth_version=a.auth_version AND a.status='active' AND a.email_verified_at IS NOT NULL AND a.archived_at IS NULL`,[digest(raw)]))[0]||null;},
 async logout(raw){if(raw)await db.query('UPDATE member_sessions SET revoked_at=UTC_TIMESTAMP(6) WHERE token_hash=?',[digest(raw)]);}
 };
}
