-- Gold Trails 001: directory foundation. MariaDB 11.8.9.
-- Apply once to an empty selected database. DDL commits implicitly.
-- No credentials or fictional creator records.
SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE schema_migrations (version VARCHAR(80) PRIMARY KEY, applied_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), description VARCHAR(255) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE regions (id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY, slug VARCHAR(160) NOT NULL UNIQUE, name VARCHAR(180) NOT NULL, region_type ENUM('country','state_province','district','river','area') NOT NULL, country_code CHAR(2) NULL, parent_region_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL, description TEXT NULL, publication_status ENUM('draft','published') NOT NULL DEFAULT 'draft', created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL,FOREIGN KEY (parent_region_id) REFERENCES regions(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CHECK (parent_region_id IS NULL OR parent_region_id <> id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE topics (id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY, slug VARCHAR(160) NOT NULL UNIQUE, name VARCHAR(180) NOT NULL, topic_group VARCHAR(80) NULL, parent_topic_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL, description TEXT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL,FOREIGN KEY (parent_topic_id) REFERENCES topics(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CHECK (parent_topic_id IS NULL OR parent_topic_id <> id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE people (id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY, slug VARCHAR(160) NOT NULL UNIQUE, display_name VARCHAR(180) NOT NULL, nickname VARCHAR(180) NULL, portrait_asset_url TEXT NULL, short_introduction VARCHAR(500) NULL, biography TEXT NULL, country_code CHAR(2) NULL, state_province VARCHAR(180) NULL, primary_region_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL, experience_since_year SMALLINT UNSIGNED NULL, offers_instruction BOOLEAN NULL, instruction_description TEXT NULL, is_sample BOOLEAN NOT NULL DEFAULT FALSE, verification_status ENUM('unverified','source_checked','creator_confirmed') NOT NULL DEFAULT 'unverified', publication_status ENUM('draft','published') NOT NULL DEFAULT 'draft', created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL,FOREIGN KEY (primary_region_id) REFERENCES regions(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CHECK (experience_since_year BETWEEN 1800 AND 2200), CHECK (offers_instruction IS NULL OR offers_instruction IN (0,1)), CHECK (is_sample IN (0,1)), INDEX people_directory (publication_status,archived_at,is_sample), INDEX people_name (display_name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE public_roles (id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE languages (id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE audience_levels (id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE formats (id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(100) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE resources (id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY, slug VARCHAR(160) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL, summary TEXT NULL, canonical_url TEXT NULL, normalized_url TEXT NULL, publisher_name VARCHAR(180) NULL, publication_date DATE NULL, publication_year SMALLINT UNSIGNED NULL, language_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL, format_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, verification_status ENUM('unverified','source_checked','creator_confirmed') NOT NULL DEFAULT 'unverified', link_status ENUM('unchecked','reachable','moved','broken') NOT NULL DEFAULT 'unchecked', last_checked_at DATETIME(6) NULL, last_http_status SMALLINT UNSIGNED NULL, publication_status ENUM('draft','published') NOT NULL DEFAULT 'draft', created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL,FOREIGN KEY (language_id) REFERENCES languages(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (format_id) REFERENCES formats(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CHECK (publication_year BETWEEN 1800 AND 2200), CHECK (publication_date IS NULL OR publication_year IS NULL OR YEAR(publication_date)=publication_year), CHECK (last_http_status BETWEEN 100 AND 599), CHECK (publication_status <> 'published' OR (canonical_url IS NOT NULL AND CHAR_LENGTH(TRIM(canonical_url)) > 0)), INDEX resources_public (publication_status,archived_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE source_references (id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY, resource_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, section_locator VARCHAR(255) NULL, video_timestamp_seconds INT UNSIGNED NULL, quotation_excerpt VARCHAR(1000) NULL, evidence_note TEXT NOT NULL, accessed_at DATETIME(6) NOT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL,FOREIGN KEY (resource_id) REFERENCES resources(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE person_aliases (id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY, person_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, alias VARCHAR(180) NOT NULL, alias_type ENUM('nickname','former_name','alternate_spelling') NOT NULL, source_reference_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL,FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (source_reference_id) REFERENCES source_references(id) ON DELETE RESTRICT ON UPDATE RESTRICT, UNIQUE(person_id,alias,alias_type), INDEX aliases_name(alias)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE person_public_roles (person_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, role_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, source_reference_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL, PRIMARY KEY (person_id,role_id),FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (role_id) REFERENCES public_roles(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (source_reference_id) REFERENCES source_references(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE person_languages (person_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, language_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, source_reference_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL, PRIMARY KEY (person_id,language_id),FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (language_id) REFERENCES languages(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (source_reference_id) REFERENCES source_references(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE person_audience_levels (person_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, audience_level_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, source_reference_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL, PRIMARY KEY (person_id,audience_level_id),FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (audience_level_id) REFERENCES audience_levels(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (source_reference_id) REFERENCES source_references(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE person_formats (person_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, format_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, source_reference_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL, PRIMARY KEY (person_id,format_id),FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (format_id) REFERENCES formats(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (source_reference_id) REFERENCES source_references(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE person_regions (person_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, region_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, relationship_type ENUM('based_in','covers','teaches_in') NOT NULL, source_reference_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL, notes TEXT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL, PRIMARY KEY (person_id,region_id,relationship_type),FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (region_id) REFERENCES regions(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (source_reference_id) REFERENCES source_references(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE person_topics (person_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, topic_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, relationship_type ENUM('specialty','technique_demonstrated','deposit_interest','content_topic','equipment_discussed') NOT NULL, source_reference_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL, notes TEXT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL, PRIMARY KEY (person_id,topic_id,relationship_type),FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (source_reference_id) REFERENCES source_references(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE channels (id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY, person_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, platform ENUM('YouTube','Facebook','Instagram','website','podcast','other') NOT NULL, channel_name VARCHAR(180) NOT NULL, handle VARCHAR(180) NULL, canonical_url TEXT NOT NULL, external_channel_id VARCHAR(191) CHARACTER SET ascii COLLATE ascii_bin NULL, description TEXT NULL, publishing_since_year SMALLINT UNSIGNED NULL, publishing_since_basis ENUM('earliest_verified_content','creator_statement','unknown') NOT NULL DEFAULT 'unknown', verification_status ENUM('unverified','source_checked','creator_confirmed') NOT NULL DEFAULT 'unverified', link_status ENUM('unchecked','reachable','moved','broken') NOT NULL DEFAULT 'unchecked', last_checked_at DATETIME(6) NULL, publication_status ENUM('draft','published') NOT NULL DEFAULT 'draft', created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL,FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE RESTRICT ON UPDATE RESTRICT, UNIQUE(platform,external_channel_id), CHECK (publishing_since_year BETWEEN 1800 AND 2200), CHECK (publishing_since_year IS NULL OR publishing_since_basis <> 'unknown'), CHECK (CHAR_LENGTH(TRIM(canonical_url))>0)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE public_contacts (id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY, person_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, contact_type ENUM('business_email','contact_page') NOT NULL, public_value VARCHAR(500) NOT NULL, source_reference_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL, last_checked_at DATETIME(6) NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL,FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (source_reference_id) REFERENCES source_references(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CHECK(CHAR_LENGTH(TRIM(public_value))>0)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE resource_people (resource_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, person_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, relationship_type ENUM('author','presenter','featured_subject','contributor') NOT NULL, source_reference_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL, PRIMARY KEY (resource_id,person_id,relationship_type),FOREIGN KEY (resource_id) REFERENCES resources(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (source_reference_id) REFERENCES source_references(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE resource_topics (resource_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, topic_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, source_reference_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL, notes TEXT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL, PRIMARY KEY (resource_id,topic_id),FOREIGN KEY (resource_id) REFERENCES resources(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (source_reference_id) REFERENCES source_references(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE resource_regions (resource_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, region_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, source_reference_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL, notes TEXT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL, PRIMARY KEY (resource_id,region_id),FOREIGN KEY (resource_id) REFERENCES resources(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (region_id) REFERENCES regions(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (source_reference_id) REFERENCES source_references(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE resource_collections (id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY, slug VARCHAR(160) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL, description TEXT NULL, publication_status ENUM('draft','published') NOT NULL DEFAULT 'draft', created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE collection_resources (collection_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, resource_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, position INT UNSIGNED NOT NULL DEFAULT 0, editorial_note TEXT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL, PRIMARY KEY (collection_id,resource_id),FOREIGN KEY (collection_id) REFERENCES resource_collections(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (resource_id) REFERENCES resources(id) ON DELETE RESTRICT ON UPDATE RESTRICT, INDEX collection_resources_ordering(collection_id,position,resource_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE person_featured_resources (person_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, resource_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, position INT UNSIGNED NOT NULL DEFAULT 0, editorial_note TEXT NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL, PRIMARY KEY (person_id,resource_id),FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (resource_id) REFERENCES resources(id) ON DELETE RESTRICT ON UPDATE RESTRICT, INDEX person_featured_resources_ordering(person_id,position,resource_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE person_fact_sources (id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY, person_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, field_key ENUM('display_name','nickname','portrait_asset_url','short_introduction','biography','country_code','state_province','primary_region_id','experience_since_year','offers_instruction','instruction_description') NOT NULL, source_reference_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, assessment ENUM('supports','disputes') NOT NULL, reviewer_note TEXT NULL, reviewed_at DATETIME(6) NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL,FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (source_reference_id) REFERENCES source_references(id) ON DELETE RESTRICT ON UPDATE RESTRICT, UNIQUE(person_id,field_key,source_reference_id,assessment)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE channel_fact_sources (id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY, channel_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, field_key ENUM('channel_name','handle','canonical_url','external_channel_id','description','publishing_since_year') NOT NULL, source_reference_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL, assessment ENUM('supports','disputes') NOT NULL, reviewer_note TEXT NULL, reviewed_at DATETIME(6) NULL, created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), archived_at DATETIME(6) NULL,FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE RESTRICT ON UPDATE RESTRICT,FOREIGN KEY (source_reference_id) REFERENCES source_references(id) ON DELETE RESTRICT ON UPDATE RESTRICT, UNIQUE(channel_id,field_key,source_reference_id,assessment)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO public_roles(id,code,name) VALUES ('159e5098-c72d-5da4-955f-04f43b9c38fd','prospector','Prospector');

INSERT INTO public_roles(id,code,name) VALUES ('2174a460-e803-5669-ac16-e8c825aa6d66','educator','Educator');

INSERT INTO public_roles(id,code,name) VALUES ('7f04f59f-e31c-56af-a11f-117a7eedf7e8','inventor','Inventor');

INSERT INTO public_roles(id,code,name) VALUES ('af7cdf1c-aee2-5abf-a3c8-aa20bdde634a','manufacturer','Manufacturer');

INSERT INTO public_roles(id,code,name) VALUES ('6e091eee-381b-5d79-8593-6d4d6305a612','seller','Seller');

INSERT INTO public_roles(id,code,name) VALUES ('1b11d4bb-decb-5e80-9cca-3d1ecf4d1f6a','creator','Creator');

INSERT INTO audience_levels(id,code,name) VALUES ('7af016f9-e0c9-5bac-9afc-125337f66c08','beginner','Beginner');

INSERT INTO audience_levels(id,code,name) VALUES ('d5941438-20fa-5ec9-85cd-351421854b4f','intermediate','Intermediate');

INSERT INTO audience_levels(id,code,name) VALUES ('e2eb3117-0d2a-547c-b53e-f0926c07e843','advanced','Advanced');

INSERT INTO formats(id,code,name) VALUES ('29ff7b02-5121-5da0-848c-1ce71f35fc02','video','Video');

INSERT INTO formats(id,code,name) VALUES ('93f46b7c-9b41-586b-ad53-1aa344c7ff6c','article','Article');

INSERT INTO formats(id,code,name) VALUES ('09ffd6de-a327-5110-a671-b5fd93ff67a1','podcast','Podcast');

INSERT INTO formats(id,code,name) VALUES ('d0a56545-ff7d-5fe5-a0ed-7589440509fc','livestream','Livestream');

INSERT INTO formats(id,code,name) VALUES ('71840058-d7b5-5da2-8fa4-a4a630636fd1','field_notes','Field Notes');

INSERT INTO schema_migrations(version,description) VALUES ('001_directory_foundation','Profiles, vocabularies, resources, relationships and evidence');
